In [6]:
!pip install hydra-core --upgrade

Collecting hydra-core
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: omegaconf<2.4,>=2.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (4.9.3)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (25.0)
Requirement already satisfied: PyYAML>=5.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from omegaconf<2.4,>=2.2->hydra-core) (6.0)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Installing collected packages: hydra-core
Successfully installed hydra-core-1.3.2

In [7]:
#from .confidence_extraction_methods import ConfidenceExtractor
#from .datasets import load_dataset
#from .metrics import MetricEvaluator
from omegaconf import OmegaConf, DictConfig
import hydra
import logging
import os
from hydra.core.hydra_config import HydraConfig
import pandas as pd

In [19]:
@hydra.main(config_path="configs", config_name="config", version_base=None)
def main(cfg):
    print(cfg)
    print("Done")

In [20]:
if __name__ == "__main__":
    main()

usage: ipykernel_launcher.py [--help] [--hydra-help] [--version]
                             [--cfg {job,hydra,all}] [--resolve]
                             [--package PACKAGE] [--run] [--multirun]
                             [--shell-completion] [--config-path CONFIG_PATH]
                             [--config-name CONFIG_NAME]
                             [--config-dir CONFIG_DIR]
                             [--experimental-rerun EXPERIMENTAL_RERUN]
                             [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                             [overrides ...]
ipykernel_launcher.py: error: unrecognized arguments: --f=c:\Users\user\AppData\Roaming\jupyter\runtime\kernel-v3dbfeee6ba1e72864561ab7ef018b73233a658064.json

SystemExit: 2

In [6]:
!pip install datasets --upgrade

Collecting datasets
  Downloading datasets-4.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.3.2)
Requirement already satisfied: requests>=2.32.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.32.3)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tqdm>=4.66.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py311-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (6.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.5.0)
Requirement already satisfied: certifi in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (2025.1.31)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (23.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: colorama in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.7.0-py3-none-any.whl (527 kB)
   ---------------------------------------- 0.0/527.5 kB ? eta -:--:--
   ---------------------------------------- 527.5/527.5 kB 16.6 MB/s  0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading multiprocess-0.70.18-py311-none-any.whl (144 kB)
Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl (457 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Installing collected packages: xxhash, propcache, multidict, h11, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, httpcore, aiosignal, httpx, aiohttp, datasets

   -------------- -------------------------  5/14 [dill]
   -------------- -------------------------  5/14 [dill]
   ---------------------- -----------------  8/14 [multiprocess]
   ------------------------- --------------  9/14 [httpcore]
   ------------------------------- -------- 11/14 [httpx]
   ---------------------------------- ----- 12/14 [aiohttp]
   ---------------------------------- ----- 12/14 [aiohttp]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ---------------------------------------- 14/14 [datasets]

Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 datasets-4.7.0 dill-0.4.0 frozenlist-1.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 multidict-6.7.1 multiprocess-0.70.18 propcache-0.4.1 xxhash-3.6.0 yarl-1.23.0

In [4]:
from datasets import load_dataset

ds = load_dataset("tau/commonsense_qa")
df = ds["train"].to_pandas()

df.head(5)

,id,question,question_concept,choices,answerKey
0,075e483d21c29a511267ef62bedc0461,The sanctions against the school were a punish...,punishing,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,61fe6e879ff18686d7552425a36344c8,Sammy wanted to go to where the people were. ...,people,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,4c1cb0e95b99f72d55c068ba0255c54d,To locate a choker not located in a jewelry bo...,choker,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,02e821a3e53cb320790950aab4489e85,Google Maps and other highway and street GPS s...,highway,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,23505889b94e880c3e89cff4ba119860,"The fox walked from the city into the forest, ...",fox,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9741 entries, 0 to 9740
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                9741 non-null   object
 1   question          9741 non-null   object
 2   question_concept  9741 non-null   object
 3   choices           9741 non-null   object
 4   answerKey         9741 non-null   object
dtypes: object(5)
memory usage: 380.6+ KB

In [7]:
df_filtered_col = df[["question", "choices", "answerKey"]]
df_filtered_col.head(5)

,question,choices,answerKey
0,The sanctions against the school were a punish...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,Sammy wanted to go to where the people were. ...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,To locate a choker not located in a jewelry bo...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,Google Maps and other highway and street GPS s...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,"The fox walked from the city into the forest, ...","{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [3]:
import pandas as pd
def get_data(data_path):
    return pd.read_csv(data_path, encoding='utf-8')

In [34]:
df1 = get_data("Our code\\experiments\\datasets\\data\\nq_open.csv")

In [35]:
df1.keys()

Index(['Unnamed: 0', 'type', 'category', 'question', 'best_answer',
       'correct_answers', 'incorrect_answers', 'source', 'problem', 'answer'],
      dtype='object')

In [36]:
question = df1['question'][0]
truth = df1['answer'][0]
print(question)
print(truth)

when was the last time anyone was on the moon
14 december 1972 utc